<template>
  <tool-shell title="Excel 快捷键" desc="Excel 常用快捷键，支持 Windows 与 Mac" icon="excel" color="#FAAD14" back-path="/tools/other">
    <doc-list :rows="rows" :columns="columns" />
    <template #status>
      <span class="status-dot"></span>
      <span>{{ rows.length }} 条记录</span>
      <span class="status-right">支持搜索</span>
    </template>
  </tool-shell>
</template>

<script setup>
import ToolShell from '@/components/tool/ToolShell.vue'
import DocList from '@/components/tool/DocList.vue'

// Excel 快捷键速查：数据迁移自旧项目 excel 模块（分类展平为列表）
defineOptions({ name: 'OtherExcelShortcut' })

const columns = [
        { key: 'category', title: '分类' },
        { key: 'name', title: '名称' },
        { key: 'win', title: 'Windows', mono: true, copy: true },
        { key: 'mac', title: 'Mac', mono: true, copy: true },
        { key: 'description', title: '说明' }
]

const rows = [
        { category: '常用快捷键', name: '关闭工作簿', win: 'Ctrl+W', mac: '⌘+W', description: '关闭当前工作簿' },
        { category: '常用快捷键', name: '打开工作簿', win: 'Ctrl+O', mac: '⌘+O', description: '打开已有工作簿' },
        { category: '常用快捷键', name: '转至“主页”选项卡', win: 'Alt+H', mac: 'Ctrl+Option+H', description: '激活主页选项卡' },
        { category: '常用快捷键', name: '保存工作簿', win: 'Ctrl+S', mac: '⌘+S', description: '保存当前工作簿' },
        { category: '常用快捷键', name: '复制', win: 'Ctrl+C', mac: '⌘+C', description: '复制选中内容' },
        { category: '常用快捷键', name: '粘贴', win: 'Ctrl+V', mac: '⌘+V', description: '粘贴剪贴板内容' },
        { category: '常用快捷键', name: '撤消', win: 'Ctrl+Z', mac: '⌘+Z', description: '撤销上一步操作' },
        { category: '常用快捷键', name: '删除单元格内容', win: 'Delete', mac: 'Delete', description: '删除选中单元格的内容' },
        { category: '常用快捷键', name: '选择填充颜色', win: 'Alt+H, H', mac: 'Ctrl+Option+H, H', description: '选择填充颜色' },
        { category: '常用快捷键', name: '剪切', win: 'Ctrl+X', mac: '⌘+X', description: '剪切选中内容' },
        { category: '常用快捷键', name: '转至“插入”选项卡', win: 'Alt+N', mac: 'Ctrl+Option+N', description: '激活插入选项卡' },
        { category: '常用快捷键', name: '加粗', win: 'Ctrl+B', mac: '⌘+B', description: '设置加粗字体' },
        { category: '常用快捷键', name: '居中对齐单元格内容', win: 'Alt+H, A, C', mac: 'Ctrl+Option+H, A, C', description: '居中对齐' },
        { category: '常用快捷键', name: '转至“页面布局”选项卡', win: 'Alt+P', mac: 'Ctrl+Option+P', description: '激活页面布局选项卡' },
        { category: '常用快捷键', name: '转至“数据”选项卡', win: 'Alt+A', mac: 'Ctrl+Option+A', description: '激活数据选项卡' },
        { category: '常用快捷键', name: '转至“视图”选项卡', win: 'Alt+W', mac: 'Ctrl+Option+W', description: '激活视图选项卡' },
        { category: '常用快捷键', name: '打开上下文菜单', win: 'Shift+F10 或 上下文键', mac: 'Shift+F10', description: '打开右键菜单' },
        { category: '常用快捷键', name: '添加边框', win: 'Alt+H, B', mac: 'Ctrl+Option+H, B', description: '添加单元格边框' },
        { category: '常用快捷键', name: '删除列', win: 'Alt+H, D, C', mac: 'Ctrl+Option+H, D, C', description: '删除选中列' },
        { category: '常用快捷键', name: '转至“公式”选项卡', win: 'Alt+M', mac: 'Ctrl+Option+M', description: '激活公式选项卡' },
        { category: '常用快捷键', name: '隐藏选定的行', win: 'Ctrl+9', mac: '⌘+9', description: '隐藏选中的行' },
        { category: '常用快捷键', name: '隐藏选定的列', win: 'Ctrl+0', mac: '⌘+0', description: '隐藏选中的列' },
        { category: '通过键盘使用功能区', name: '选择功能区的活动选项卡并激活访问键', win: 'Alt 或 F10', mac: 'Control+F2（显示访问键后按对应字母）', description: '' },
        { category: '通过键盘使用功能区', name: '将焦点移到功能区上的命令', win: 'Tab 或 Shift+Tab', mac: 'Tab 或 Shift+Tab', description: '' },
        { category: '通过键盘使用功能区', name: '分别在功能区上的各项之间向下、向上、向左或向右移动', win: '向下、向上、向左或向右箭头键', mac: '向下、向上、向左或向右箭头键', description: '' },
        { category: '通过键盘使用功能区', name: '激活所选按钮', win: '空格键或 Enter', mac: '空格键或 Return', description: '' },
        { category: '通过键盘使用功能区', name: '打开所选命令的列表', win: '向下键', mac: '向下键', description: '' },
        { category: '通过键盘使用功能区', name: '打开所选按钮的菜单', win: 'Alt+向下箭头键', mac: 'Option+向下箭头键', description: '' },
        { category: '通过键盘使用功能区', name: '当菜单或子菜单处于打开状态时，移到下一条命令', win: '向下键', mac: '向下键', description: '' },
        { category: '通过键盘使用功能区', name: '展开或折叠功能区', win: 'Ctrl+F1', mac: 'Command+F1', description: '' },
        { category: '通过键盘使用功能区', name: '打开上下文菜单', win: 'Shift+F10', mac: 'Control+F10', description: '' },
        { category: '通过键盘使用功能区', name: '当主菜单处于打开或选中状态时，移到子菜单', win: '向左键', mac: '向左键', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '移到工作表中的前一个单元格或对话框中的前一个选项', win: 'Shift+Tab', mac: 'Shift+Tab', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在工作表中向上移动一个单元格', win: '向上键', mac: '向上键', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在工作表中向下移动一个单元格', win: '向下键', mac: '向下键', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在工作表中向左移动一个单元格', win: '向左键', mac: '向左键', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在工作表中向右移动一个单元格', win: '向右键', mac: '向右键', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '移到工作表中当前数据区域的边缘', win: 'Ctrl + 箭头键', mac: 'Command+箭头键', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '移到工作表上的最后一个单元格，即所使用的最右一列的最下面一行', win: 'Ctrl+End', mac: 'Command+End', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '将单元格选定区域扩展至工作表上最后一个使用的单元格（右下角）', win: 'Ctrl+Shift+End', mac: 'Command+Shift+End', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '当 Scroll Lock 处于开启状态时，移到窗口左上角的单元格', win: 'Home+Scroll Lock', mac: 'Home+Scroll Lock', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '移到工作表的开头', win: 'Ctrl+Home', mac: 'Command+Home', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在工作表中向下移动一屏', win: 'Page Down', mac: 'Page Down', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '移到工作簿中的下一个工作表', win: 'Ctrl+Page Down', mac: 'Command+Page Down', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在工作表中向右移动一屏', win: 'Alt+Page Down', mac: 'Option+Page Down', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在工作表中向上移动一屏', win: 'Page Up', mac: 'Page Up', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在工作表中向左移动一屏', win: 'Alt+Page Up', mac: 'Option+Page Up', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '移到工作簿中的上一个工作表', win: 'Ctrl+Page Up', mac: 'Command+Page Up', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在工作表中向右移动一个单元格。或者，在受保护的工作表中，在未锁定的单元格之间移动', win: 'Tab', mac: 'Tab', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '在应用了数据验证选项的单元格上打开验证选项列表', win: 'Alt+向下箭头键', mac: 'Option+向下箭头键', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '环绕文本框或图像等浮动形状', win: '按 Ctrl + Alt + 5, 然后重复按 Tab 键', mac: '按 Command + Option + 5, 然后重复按 Tab 键', description: '' },
        { category: '用于单元格导航的键盘快捷键', name: '退出浮动形状导航并返回普通导航', win: 'Esc', mac: 'Esc', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '打开“设置单元格格式”对话框', win: 'Ctrl+1', mac: 'Command+1', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '在“设置单元格格式”对话框中设置字体格式', win: 'Ctrl+Shift+F 或 Ctrl+Shift+P', mac: 'Command+Shift+F 或 Command+Shift+P', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '编辑活动单元格，并将插入点放在其内容的末尾。或者，如果单元格的编辑已关闭，则将插入点移到编辑栏中。如果编辑公式，请关闭或打开点模式，以便你可以使用箭头键创建引用', win: 'F2', mac: 'F2（或 Fn+F2）', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '添加或编辑单元格批注', win: 'Shift+F2', mac: 'Shift+F2（或 Shift+Fn+F2）', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '打开用于插入空白单元格的“插入”对话框', win: 'Ctrl+Shift+加号 (+)', mac: 'Command+Shift+加号 (+)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '打开用于删除选定单元格的“删除”对话框', win: 'Ctrl+减号 (-)', mac: 'Command+减号 (-)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '输入当前时间', win: 'Ctrl+Shift+冒号 (:)', mac: 'Command+Shift+冒号 (:)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '输入当前日期', win: 'Ctrl+分号 (;)', mac: 'Command+分号 (;)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '在工作表中，在显示单元格值或公式之间切换', win: 'Ctrl+重音符 (`)', mac: 'Command+重音符 (`)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '将公式从活动单元格上方的单元格复制到单元格或编辑栏中', win: 'Ctrl+撇号 (\')', mac: 'Command+撇号 (\')', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '移动选定的单元格', win: 'Ctrl+X', mac: 'Command+X', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '复制选定的单元格', win: 'Ctrl+C', mac: 'Command+C', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '在插入点粘贴内容，并替换任何所选内容', win: 'Ctrl+V', mac: 'Command+V', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '打开“选择性粘贴”对话框', win: 'Ctrl+Alt+V', mac: 'Command+Option+V', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '将文本设置为斜体或删除倾斜格式', win: 'Ctrl+I 或 Ctrl+3', mac: 'Command+I 或 Command+3', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '将文本设置为加粗或删除加粗格式', win: 'Ctrl+B 或 Ctrl+2', mac: 'Command+B 或 Command+2', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '为文字添加下划线或删除下划线', win: 'Ctrl+U 或 Ctrl+4', mac: 'Command+U 或 Command+4', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '应用或删除删除线格式', win: 'Ctrl+5', mac: 'Command+5', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '在隐藏对象、显示对象和显示对象的占位符之间切换', win: 'Ctrl+6', mac: 'Command+6', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '将轮廓边框应用于选定单元格', win: 'Ctrl+Shift+与号 (&)', mac: 'Command+Shift+与号 (&)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '从选定单元格中删除轮廓边框', win: 'Ctrl+Shift+下划线 (_)', mac: 'Command+Shift+下划线 (_)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '显示或隐藏大纲符号', win: 'Ctrl+8', mac: 'Command+8', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '使用“向下填充”命令将选定范围内最顶层单元格的内容和格式复制到下面的单元格中', win: 'Ctrl+D', mac: 'Command+D', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '应用“常规”数字格式', win: 'Ctrl+Shift+波形符 (~)', mac: 'Command+Shift+波形符 (~)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '应用带有两位小数的“货币”格式（负数放在括号中）', win: 'Ctrl+Shift+美元符号 ($)', mac: 'Command+Shift+美元符号 ($)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '应用不带小数位的“百分比”格式', win: 'Ctrl+Shift+百分比 (%)', mac: 'Command+Shift+百分比 (%)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '应用带有两位小数的科学计数格式', win: 'Ctrl+Shift+脱字号 (^)', mac: 'Command+Shift+脱字号 (^)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '应用带有日、月和年的“日期”格式', win: 'Ctrl+Shift+数字符号 (#)', mac: 'Command+Shift+数字符号 (#)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '应用带有小时和分钟以及 AM 或 PM 的“时间”格式', win: 'Ctrl+Shift+@ 符号 (@)', mac: 'Command+Shift+@ 符号 (@)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '应用带有两位小数、千分位分隔符和减号 (-)（用于负值）的“数值”格式', win: 'Ctrl+Shift+感叹号 (!)', mac: 'Command+Shift+感叹号 (!)', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '打开“插入超链接”对话框', win: 'Ctrl+K', mac: 'Command+K', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '检查活动工作表或选定范围中的拼写', win: 'F7', mac: 'F7（或 Fn+F7）', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '显示用于包含数据的选定单元格的“快速分析”选项', win: 'Ctrl+Q', mac: 'Command+Q', description: '' },
        { category: '用于单元格格式设置的键盘快捷键', name: '显示“创建表”对话框', win: 'Ctrl+L 或 Ctrl+T', mac: 'Command+L 或 Command+T', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '选择整个工作表', win: 'Ctrl+A 或 Ctrl+Shift+空格键', mac: 'Command+A 或 Command+Shift+空格键', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '选择工作簿中的当前和下一个工作表', win: 'Ctrl+Shift+Page Down', mac: 'Command+Shift+Page Down', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '选择工作簿中的当前和上一个工作表', win: 'Ctrl+Shift+Page Up', mac: 'Command+Shift+Page Up', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '将单元格的选定范围扩大一个单元格', win: 'Shift+箭头键', mac: 'Shift+箭头键', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '将单元格的选定范围扩展到活动单元格所在列或行中的最后一个非空单元格，或者如果下一个单元格为空，则扩展到下一个非空单元格', win: 'Ctrl + Shift + 箭头键', mac: 'Command + Shift + 箭头键', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '打开扩展模式并使用箭头键扩展选定范围。再次按下以关闭', win: 'F8', mac: 'F8（或 Fn+F8）', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '通过使用箭头键将非邻近单元格或区域添加到单元格的选定范围中', win: 'Shift+F8', mac: 'Shift+F8（或 Shift+Fn+F8）', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '在同一单元格中另起一个新行', win: 'Alt+Enter', mac: 'Option+Return', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '使用当前输入填充选定的单元格区域', win: 'Ctrl+Enter', mac: 'Command+Return', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '完成单元格输入并选择上面的单元格', win: 'Shift+Enter', mac: 'Shift+Return', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '选择工作表中的整列', win: 'Ctrl+空格键', mac: 'Control+空格键', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '选择工作表中的整行', win: 'Shift+空格键', mac: 'Shift+空格键', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '当某个对象处于选定状态时，选择工作表上的所有对象', win: 'Ctrl+Shift+空格键', mac: 'Command+Shift+空格键', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '将单元格的选定范围扩展到工作表的开头', win: 'Ctrl+Shift+Home', mac: 'Command+Shift+Home', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '如果工作表包含数据，则选择当前区域。再按一次将选择当前区域和其摘要行。按第三次将选择整个工作表', win: 'Ctrl+A 或 Ctrl+Shift+空格键', mac: 'Command+A 或 Command+Shift+空格键', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '选择环绕活动单元格的当前区域或选择整个数据透视表', win: 'Ctrl+Shift+星号 (*)', mac: 'Command+Shift+星号 (*)', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '当菜单或子菜单处于可见状态时，选择菜单上的第一个命令', win: 'Home', mac: 'Home', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '重复上一个命令或操作（如有可能）', win: 'Ctrl+Y', mac: 'Command+Y 或 Command+Shift+Z', description: '' },
        { category: '进行选择并执行操作的键盘快捷键', name: '撤消最后一个操作', win: 'Ctrl+Z', mac: 'Command+Z', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '键入公式', win: '=（等号）', mac: '=（等号）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '将公式作为数组公式输入', win: 'Ctrl+Shift+Enter', mac: 'Command+Shift+Return', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '用SUM函数插入“自动求和”公式', win: 'Alt+=（等号）', mac: 'Option+=（等号）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '选择整个数据透视表', win: 'Ctrl+Shift+星号 (*)', mac: 'Command+Shift+星号 (*)', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '编辑活动单元格，并将插入点放在其内容的末尾。或者，如果单元格的编辑已关闭，则将插入点移到编辑栏中。如果编辑公式，请关闭或打开点模式，以便你可以使用箭头键创建引用', win: 'F2', mac: 'F2（或 Fn+F2）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '展开或折叠编辑栏', win: 'Ctrl+Shift+U', mac: 'Command+Shift+U', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '取消单元格或编辑栏中的输入', win: 'Esc', mac: 'Esc', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '完成编辑栏中的输入并选择下面的单元格', win: 'Enter', mac: 'Return', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '在编辑栏中时，将光标移到文本的末尾', win: 'Ctrl+End', mac: 'Command+End', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '选择编辑栏中从光标所在的位置到结尾的所有文本', win: 'Ctrl+Shift+End', mac: 'Command+Shift+End', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '计算所有打开的工作簿中的所有工作表', win: 'F9', mac: 'F9（或 Fn+F9）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '计算活动工作表', win: 'Shift+F9', mac: 'Shift+F9（或 Shift+Fn+F9）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '计算所有打开的工作簿中的所有工作表，不管自上次计算以来它们是否已更改', win: 'Ctrl+Alt+F9', mac: 'Command+Option+F9（或 Command+Option+Fn+F9）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '检查从属的公式，然后计算所有打开的工作簿中的所有单元格，其中包括未标记为需要计算的单元格', win: 'Ctrl+Alt+Shift+F9', mac: 'Command+Option+Shift+F9（或 Command+Option+Shift+Fn+F9）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '显示“错误检查”按钮的菜单或消息', win: 'Alt+Shift+F10', mac: 'Option+Shift+F10（或 Option+Shift+Fn+F10）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '当插入点位于公式中某个函数名称的右边时，会显示“函数参数”对话框', win: 'Ctrl+A', mac: 'Command+A', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '当插入点位于公式中某个函数名称的右边时，会插入参数名称和括号', win: 'Ctrl+Shift+A', mac: 'Command+Shift+A', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '调用快速填充以自动识别相邻列中的模式并填充当前列', win: 'Ctrl+E', mac: 'Command+E', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '如果选定了单元格引用或范围，则会在公式中的绝对和相对引用的所有各种组合之间循环切换', win: 'F4', mac: 'F4（或 Fn+F4）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '插入函数', win: 'Shift+F3', mac: 'Shift+F3（或 Shift+Fn+F3）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '将活动单元格上方的单元格的值复制到单元格或编辑栏中', win: 'Ctrl+Shift+直双引号 (")', mac: 'Command+Shift+直双引号 (")', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '在当前范围中创建数据的嵌入图表', win: 'Alt+F1', mac: 'Option+F1（或 Option+Fn+F1）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '在单独的图表工作表中创建当前范围内数据的图表', win: 'F11', mac: 'F11（或 Fn+F11）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '定义名称以在引用中使用', win: 'Alt+M, M, D', mac: 'Option+M, M, D', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '从“粘贴名称”对话框中粘贴名称（在工作簿中已定义名称的情况下）', win: 'F3', mac: 'F3（或 Fn+F3）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '移到数据表单下一条记录中的第一个字段', win: 'Enter', mac: 'Return', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '创建、运行、编辑或删除宏', win: 'Alt+F8', mac: 'Option+F8（或 Option+Fn+F8）', description: '' },
        { category: '用于处理数据、函数和编辑栏的键盘快捷键', name: '打开 Microsoft Visual Basic For Applications Editor', win: 'Alt+F11', mac: 'Option+F11（或 Option+Fn+F11）', description: '' },
        { category: '功能键', name: '显示“Excel 帮助”任务窗格', win: 'F1', mac: 'F1（或 Fn+F1）', description: '' },
        { category: '功能键', name: '显示或隐藏功能区', win: 'Ctrl+F1', mac: 'Command+F1', description: '' },
        { category: '功能键', name: '在当前区域中创建数据的嵌入图表', win: 'Alt+F1', mac: 'Option+F1（或 Option+Fn+F1）', description: '' },
        { category: '功能键', name: '插入新的工作表', win: 'Alt+Shift+F1', mac: 'Option+Shift+F1（或 Option+Shift+Fn+F1）', description: '' },
        { category: '功能键', name: '编辑活动单元格，并将插入点放在其内容的末尾。或者，如果单元格的编辑已关闭，则将插入点移到编辑栏中。如果编辑公式，请关闭或打开点模式，以便你可以使用箭头键创建引用', win: 'F2', mac: 'F2（或 Fn+F2）', description: '' },
        { category: '功能键', name: '添加或编辑单元格批注', win: 'Shift+F2', mac: 'Shift+F2（或 Shift+Fn+F2）', description: '' },
        { category: '功能键', name: '显示 Backstage 视图 中“打印”选项卡上的打印预览区域', win: 'Ctrl+F2', mac: 'Command+F2（或 Command+Fn+F2）', description: '' },
        { category: '功能键', name: '显示“粘贴名称”对话框。仅适用于在工作簿中已定义名称的情况', win: 'F3', mac: 'F3（或 Fn+F3）', description: '' },
        { category: '功能键', name: '显示“插入函数”对话框', win: 'Shift+F3', mac: 'Shift+F3（或 Shift+Fn+F3）', description: '' },
        { category: '功能键', name: '重复上一个命令或操作（如有可能）。当公式中选定单元格引用或区域时，按 F4 可在绝对和相对引用的所有各种组合中循环切换', win: 'F4', mac: 'F4（或 Fn+F4）', description: '' },
        { category: '功能键', name: '关闭选定的工作簿窗口', win: 'Ctrl+F4', mac: 'Command+W', description: '' },
        { category: '功能键', name: '关闭 Excel', win: 'Alt+F4', mac: 'Command+Q', description: '' },
        { category: '功能键', name: '显示“定位”对话框', win: 'F5', mac: 'F5（或 Fn+F5）', description: '' },
        { category: '功能键', name: '恢复选定工作簿窗口的窗口大小', win: 'Ctrl+F5', mac: 'Command+F5（或 Command+Fn+F5）', description: '' },
        { category: '功能键', name: '在工作表、功能区、任务窗格和缩放控件之间切换。在已拆分的工作表中，在窗格和功能区区域之间切换时，按 F6 可包括已拆分的窗格', win: 'F6', mac: 'F6（或 Fn+F6）', description: '' },
        { category: '功能键', name: '在工作表、缩放控件、任务窗格和功能区之间切换', win: 'Shift+F6', mac: 'Shift+F6（或 Shift+Fn+F6）', description: '' },
        { category: '功能键', name: '如果打开了多个工作簿窗口，按 Ctrl+F6 可切换到下一个工作簿窗口', win: 'Ctrl+F6', mac: 'Command+F6（或 Command+Fn+F6）', description: '' },
        { category: '功能键', name: '打开“拼写检查”对话框，用于检查活动工作表或选定范围中的拼写', win: 'F7', mac: 'F7（或 Fn+F7）', description: '' },
        { category: '功能键', name: '如果工作簿窗口未最大化，则按 Ctrl+F7 可对该窗口执行“移动”命令。使用箭头键移动窗口，并在完成时按 Enter，或按 Esc 取消', win: 'Ctrl+F7', mac: 'Command+F7（或 Command+Fn+F7）', description: '' },
        { category: '功能键', name: '打开或关闭扩展模式。在扩展模式中，“扩展选定”将出现在状态行中，并且按箭头键可扩展选定范围', win: 'F8', mac: 'F8（或 Fn+F8）', description: '' },
        { category: '功能键', name: '允许您使用箭头键将非邻近单元格或区域添加到单元格的选定范围中', win: 'Shift + F8', mac: 'Shift + F8（或 Shift + Fn+F8）', description: '' },
        { category: '功能键', name: '当工作簿未最大化时，执行“大小”命令', win: 'Ctrl+F8', mac: 'Command+F8（或 Command+Fn+F8）', description: '' },
        { category: '功能键', name: '显示“宏”对话框，用于创建、运行、编辑或删除宏', win: 'Alt+F8', mac: 'Option+F8（或 Option+Fn+F8）', description: '' },
        { category: '功能键', name: '计算所有打开的工作簿中的所有工作表', win: 'F9', mac: 'F9（或 Fn+F9）', description: '' },
        { category: '功能键', name: '计算活动工作表', win: 'Shift+F9', mac: 'Shift+F9（或 Shift+Fn+F9）', description: '' },
        { category: '功能键', name: '计算所有打开的工作簿中的所有工作表，不管它们自上次计算以来是否已更改', win: 'Ctrl+Alt+F9', mac: 'Command+Option+F9（或 Command+Option+Fn+F9）', description: '' },
        { category: '功能键', name: '重新检查从属的公式，然后计算所有打开的工作簿中的所有单元格，其中包括未标记为需要计算的单元格', win: 'Ctrl+Alt+Shift+F9', mac: 'Command+Option+Shift+F9（或 Command+Option+Shift+Fn+F9）', description: '' },
        { category: '功能键', name: '将工作簿窗口最小化为图标', win: 'Ctrl+F9', mac: 'Command+F9（或 Command+Fn+F9）', description: '' },
        { category: '功能键', name: '打开或关闭快捷键提示。（按 Alt 也能实现同样目的）', win: 'F10', mac: 'F10（或 Fn+F10）', description: '' },
        { category: '功能键', name: '显示选定项目的快捷菜单', win: 'Shift+F10', mac: 'Shift+F10（或 Shift+Fn+F10）', description: '' },
        { category: '功能键', name: '显示“错误检查”按钮的菜单或消息', win: 'Alt+Shift+F10', mac: 'Option+Shift+F10（或 Option+Shift+Fn+F10）', description: '' },
        { category: '功能键', name: '最大化或还原选定的工作簿窗口', win: 'Ctrl+F10', mac: 'Command+F10（或 Command+Fn+F10）', description: '' },
        { category: '功能键', name: '在单独的图表工作表中创建当前范围内数据的图表', win: 'F11', mac: 'F11（或 Fn+F11）', description: '' },
        { category: '功能键', name: '插入一个新工作表', win: 'Shift+F11', mac: 'Shift+F11（或 Shift+Fn+F11）', description: '' },
        { category: '功能键', name: '打开 Microsoft Visual Basic For Applications 编辑器，你可以在该编辑器中通过使用 Visual Basic for Applications (VBA) 来创建宏', win: 'Alt+F11', mac: 'Option+F11（或 Option+Fn+F11）', description: '' },
        { category: '功能键', name: '显示“另存为”对话框', win: 'F12', mac: 'F12（或 Fn+F12）', description: '' },
        { category: '功能区选项卡访问键', name: '操作说明搜索框', win: 'Alt+Q', mac: 'Command+Option+Q', description: '定位到操作说明搜索框' },
        { category: '功能区选项卡访问键', name: '打开“文件”页面', win: 'Alt+F', mac: 'Command+Option+F', description: '打开文件菜单' },
        { category: '功能区选项卡访问键', name: '打开“主页”选项卡', win: 'Alt+H', mac: 'Command+Option+H', description: '激活主页选项卡' },
        { category: '功能区选项卡访问键', name: '打开“插入”选项卡', win: 'Alt+N', mac: 'Command+Option+N', description: '激活插入选项卡' },
        { category: '功能区选项卡访问键', name: '打开“页面布局”选项卡', win: 'Alt+P', mac: 'Command+Option+P', description: '激活页面布局选项卡' },
        { category: '功能区选项卡访问键', name: '打开“公式”选项卡', win: 'Alt+M', mac: 'Command+Option+M', description: '激活公式选项卡' },
        { category: '功能区选项卡访问键', name: '打开“数据”选项卡', win: 'Alt+A', mac: 'Command+Option+A', description: '激活数据选项卡' },
        { category: '功能区选项卡访问键', name: '打开“审阅”选项卡', win: 'Alt+R', mac: 'Command+Option+R', description: '激活审阅选项卡' },
        { category: '功能区选项卡访问键', name: '打开“视图”选项卡', win: 'Alt+W', mac: 'Command+Option+W', description: '激活视图选项卡' }
]
</script>
