<template>
  <tool-shell
    title="域名后缀查询"
    desc="国家域名缩写查询"
    icon="globe"
    color="#13C2C2"
    back-path="/tools/life"
  >
    <doc-list :rows="rows" :columns="columns" />
    <template #status>
      <span class="status-dot"></span>
      <span>{{ rows.length }} 条记录</span>
      <span class="status-right">支持搜索</span>
    </template>
  </tool-shell>
</template>

<script setup>
import { ref } from 'vue'
import ToolShell from '@/components/tool/ToolShell.vue'
import DocList from '@/components/tool/DocList.vue'

defineOptions({ name: 'LifeAreaDomain' })

// 表格列配置：后缀列等宽字体且支持点击复制
const columns = ref([
  { key: 'suffix', title: '域名后缀', mono: true, copy: true },
  { key: 'country', title: '国家或地区', tag: true },
  { key: 'name', title: '英文名称' },
  { key: 'phone', title: '电话代码', mono: true }
])
// 国家域名后缀数据，提取自旧项目 areaDomain 模块
const rows = ref([
        { suffix: '.ad', country: '安道尔共和国', name: 'Andorra', phone: '376' },
        { suffix: '.ae', country: '阿拉伯联合酋长国', name: 'United Arab Emirates', phone: '971' },
        { suffix: '.af', country: '阿富汗', name: 'Afghanistan', phone: '93' },
        { suffix: '.ag', country: '安提瓜和巴布达', name: 'Antigua and Barbuda', phone: '1268' },
        { suffix: '.ai', country: '安圭拉岛', name: 'Anguilla', phone: '1264' },
        { suffix: '.al', country: '阿尔巴尼亚', name: 'Albania', phone: '355' },
        { suffix: '.am', country: '亚美尼亚', name: 'Armenia', phone: '374' },
        { suffix: '—', country: '阿森松', name: 'Ascension', phone: '247' },
        { suffix: '.ao', country: '安哥拉', name: 'Angola', phone: '244' },
        { suffix: '.ar', country: '阿根廷', name: 'Argentina', phone: '54' },
        { suffix: '.at', country: '奥地利', name: 'Austria', phone: '43' },
        { suffix: '.au', country: '澳大利亚', name: 'Australia', phone: '61' },
        { suffix: '.az', country: '阿塞拜疆', name: 'Azerbaijan', phone: '994' },
        { suffix: '.bb', country: '巴巴多斯', name: 'Barbados', phone: '1246' },
        { suffix: '.bd', country: '孟加拉国', name: 'Bangladesh', phone: '880' },
        { suffix: '.be', country: '比利时', name: 'Belgium', phone: '32' },
        { suffix: '.bf', country: '布基纳法索', name: 'Burkina-faso', phone: '226' },
        { suffix: '.bg', country: '保加利亚', name: 'Bulgaria', phone: '359' },
        { suffix: '.bh', country: '巴林', name: 'Bahrain', phone: '973' },
        { suffix: '.bi', country: '布隆迪', name: 'Burundi', phone: '257' },
        { suffix: '.bj', country: '贝宁', name: 'Benin', phone: '229' },
        { suffix: '.bl', country: '巴勒斯坦', name: 'Palestine', phone: '970' },
        { suffix: '.bm', country: '百慕大群岛', name: 'Bermuda Is.', phone: '1441' },
        { suffix: '.bn', country: '文莱', name: 'Brunei', phone: '673' },
        { suffix: '.bo', country: '玻利维亚', name: 'Bolivia', phone: '591' },
        { suffix: '.br', country: '巴西', name: 'Brazil', phone: '55' },
        { suffix: '.bs', country: '巴哈马', name: 'Bahamas', phone: '1242' },
        { suffix: '.bw', country: '博茨瓦纳', name: 'Botswana', phone: '267' },
        { suffix: '.by', country: '白俄罗斯', name: 'Belarus', phone: '375' },
        { suffix: '.bz', country: '伯利兹', name: 'Belize', phone: '501' },
        { suffix: '.ca', country: '加拿大', name: 'Canada', phone: '1' },
        { suffix: '—', country: '开曼群岛', name: 'Cayman Is.', phone: '1345' },
        { suffix: '.cf', country: '中非共和国', name: 'Central African Republic', phone: '236' },
        { suffix: '.cg', country: '刚果', name: 'Congo', phone: '242' },
        { suffix: '.ch', country: '瑞士', name: 'Switzerland', phone: '41' },
        { suffix: '.ck', country: '库克群岛', name: 'Cook Is.', phone: '682' },
        { suffix: '.cl', country: '智利', name: 'Chile', phone: '56' },
        { suffix: '.cm', country: '喀麦隆', name: 'Cameroon', phone: '237' },
        { suffix: '.cn', country: '中国', name: 'China', phone: '86' },
        { suffix: '.co', country: '哥伦比亚', name: 'Colombia', phone: '57' },
        { suffix: '.cr', country: '哥斯达黎加', name: 'Costa Rica', phone: '506' },
        { suffix: '.cu', country: '古巴', name: 'Cuba', phone: '53' },
        { suffix: '.cy', country: '塞浦路斯', name: 'Cyprus', phone: '357' },
        { suffix: '.cz', country: '捷克', name: 'Czech Republic', phone: '420' },
        { suffix: '.de', country: '德国', name: 'Germany', phone: '49' },
        { suffix: '.dj', country: '吉布提', name: 'Djibouti', phone: '253' },
        { suffix: '.dk', country: '丹麦', name: 'Denmark', phone: '45' },
        { suffix: '.do', country: '多米尼加共和国', name: 'Dominican Republic', phone: '1809' },
        { suffix: '.dm', country: '多米尼克', name: 'Dominica', phone: '1767' },
        { suffix: '.dz', country: '阿尔及利亚', name: 'Algeria', phone: '213' },
        { suffix: '.ec', country: '厄瓜多尔', name: 'Ecuador', phone: '593' },
        { suffix: '.ee', country: '爱沙尼亚', name: 'Estonia', phone: '372' },
        { suffix: '.eg', country: '埃及', name: 'Egypt', phone: '20' },
        { suffix: '.es', country: '西班牙', name: 'Spain', phone: '34' },
        { suffix: '.et', country: '埃塞俄比亚', name: 'Ethiopia', phone: '251' },
        { suffix: '.fi', country: '芬兰', name: 'Finland', phone: '358' },
        { suffix: '.fj', country: '斐济', name: 'Fiji', phone: '679' },
        { suffix: '.fr', country: '法国', name: 'France', phone: '33' },
        { suffix: '.ga', country: '加蓬', name: 'Gabon', phone: '241' },
        { suffix: '.gb', country: '英国', name: 'United Kingdom', phone: '44' },
        { suffix: '.gd', country: '格林纳达', name: 'Grenada', phone: '1809' },
        { suffix: '.ge', country: '格鲁吉亚', name: 'Georgia', phone: '995' },
        { suffix: '.gf', country: '法属圭亚那', name: 'French Guiana', phone: '594' },
        { suffix: '.gh', country: '加纳', name: 'Ghana', phone: '233' },
        { suffix: '.gi', country: '直布罗陀', name: 'Gibraltar', phone: '350' },
        { suffix: '.gm', country: '冈比亚', name: 'Gambia', phone: '220' },
        { suffix: '.gn', country: '几内亚', name: 'Guinea', phone: '224' },
        { suffix: '.gr', country: '希腊', name: 'Greece', phone: '30' },
        { suffix: '.gt', country: '危地马拉', name: 'Guatemala', phone: '502' },
        { suffix: '.gu', country: '关岛', name: 'Guam', phone: '1671' },
        { suffix: '.gy', country: '圭亚那', name: 'Guyana', phone: '592' },
        { suffix: '.hk', country: '中国香港特别行政区', name: 'Hongkong', phone: '852' },
        { suffix: '.hn', country: '洪都拉斯', name: 'Honduras', phone: '504' },
        { suffix: '.ht', country: '海地', name: 'Haiti', phone: '509' },
        { suffix: '.hu', country: '匈牙利', name: 'Hungary', phone: '36' },
        { suffix: '.id', country: '印度尼西亚', name: 'Indonesia', phone: '62' },
        { suffix: '.ie', country: '爱尔兰', name: 'Ireland', phone: '353' },
        { suffix: '.il', country: '以色列', name: 'Israel', phone: '972' },
        { suffix: '.in', country: '印度', name: 'India', phone: '91' },
        { suffix: '.iq', country: '伊拉克', name: 'Iraq', phone: '964' },
        { suffix: '.ir', country: '伊朗', name: 'Iran', phone: '98' },
        { suffix: '.is', country: '冰岛', name: 'Iceland', phone: '354' },
        { suffix: '.it', country: '意大利', name: 'Italy', phone: '39' },
        { suffix: '—', country: '科特迪瓦', name: 'Ivory Coast', phone: '225' },
        { suffix: '.jm', country: '牙买加', name: 'Jamaica', phone: '1876' },
        { suffix: '.jo', country: '约旦', name: 'Jordan', phone: '962' },
        { suffix: '.jp', country: '日本', name: 'Japan', phone: '81' },
        { suffix: '.ke', country: '肯尼亚', name: 'Kenya', phone: '254' },
        { suffix: '.kg', country: '吉尔吉斯坦', name: 'Kyrgyzstan', phone: '331' },
        { suffix: '.kh', country: '柬埔寨', name: 'Kampuchea (Cambodia )', phone: '855' },
        { suffix: '.kp', country: '朝鲜', name: 'North Korea', phone: '850' },
        { suffix: '.kr', country: '韩国', name: 'Korea', phone: '82' },
        { suffix: '.kt', country: '科特迪瓦共和国', name: 'Republic of Ivory Coast', phone: '225' },
        { suffix: '.kw', country: '科威特', name: 'Kuwait', phone: '965' },
        { suffix: '.kz', country: '哈萨克斯坦', name: 'Kazakstan', phone: '327' },
        { suffix: '.la', country: '老挝', name: 'Laos', phone: '856' },
        { suffix: '.lb', country: '黎巴嫩', name: 'Lebanon', phone: '961' },
        { suffix: '.lc', country: '圣卢西亚', name: 'St.Lucia', phone: '1758' },
        { suffix: '.li', country: '列支敦士登', name: 'Liechtenstein', phone: '423' },
        { suffix: '.lk', country: '斯里兰卡', name: 'Sri Lanka', phone: '94' },
        { suffix: '.lr', country: '利比里亚', name: 'Liberia', phone: '231' },
        { suffix: '.ls', country: '莱索托', name: 'Lesotho', phone: '266' },
        { suffix: '.lt', country: '立陶宛', name: 'Lithuania', phone: '370' },
        { suffix: '.lu', country: '卢森堡', name: 'Luxembourg', phone: '352' },
        { suffix: '.lv', country: '拉脱维亚', name: 'Latvia', phone: '371' },
        { suffix: '.ly', country: '利比亚', name: 'Libya', phone: '218' },
        { suffix: '.ma', country: '摩洛哥', name: 'Morocco', phone: '212' },
        { suffix: '.mc', country: '摩纳哥', name: 'Monaco', phone: '377' },
        { suffix: '.md', country: '摩尔多瓦', name: 'Moldova, Republic of', phone: '373' },
        { suffix: '.mg', country: '马达加斯加', name: 'Madagascar', phone: '261' },
        { suffix: '.ml', country: '马里', name: 'Mali', phone: '223' },
        { suffix: '.mm', country: '缅甸', name: 'Burma', phone: '95' },
        { suffix: '.mn', country: '蒙古', name: 'Mongolia', phone: '976' },
        { suffix: '.mo', country: '澳门', name: 'Macao', phone: '853' },
        { suffix: '.ms', country: '蒙特塞拉特岛', name: 'Montserrat Is', phone: '1664' },
        { suffix: '.mt', country: '马耳他', name: 'Malta', phone: '356' },
        { suffix: '—', country: '马里亚那群岛', name: 'Mariana Is', phone: '1670' },
        { suffix: '—', country: '马提尼克', name: 'Martinique', phone: '596' },
        { suffix: '.mu', country: '毛里求斯', name: 'Mauritius', phone: '230' },
        { suffix: '.mv', country: '马尔代夫', name: 'Maldives', phone: '960' },
        { suffix: '.mw', country: '马拉维', name: 'Malawi', phone: '265' },
        { suffix: '.mx', country: '墨西哥', name: 'Mexico', phone: '52' },
        { suffix: '.my', country: '马来西亚', name: 'Malaysia', phone: '60' },
        { suffix: '.mz', country: '莫桑比克', name: 'Mozambique', phone: '258' },
        { suffix: '.na', country: '纳米比亚', name: 'Namibia', phone: '264' },
        { suffix: '.ne', country: '尼日尔', name: 'Niger', phone: '977' },
        { suffix: '.ng', country: '尼日利亚', name: 'Nigeria', phone: '234' },
        { suffix: '.ni', country: '尼加拉瓜', name: 'Nicaragua', phone: '505' },
        { suffix: '.nl', country: '荷兰', name: 'Netherlands', phone: '31' },
        { suffix: '.no', country: '挪威', name: 'Norway', phone: '47' },
        { suffix: '.np', country: '尼泊尔', name: 'Nepal', phone: '977' },
        { suffix: '—', country: '荷属安的列斯', name: 'Netheriands Antilles', phone: '599' },
        { suffix: '.nr', country: '瑙鲁', name: 'Nauru', phone: '674' },
        { suffix: '.nz', country: '新西兰', name: 'New Zealand', phone: '64' },
        { suffix: '.om', country: '阿曼', name: 'Oman', phone: '968' },
        { suffix: '.pa', country: '巴拿马', name: 'Panama', phone: '507' },
        { suffix: '.pe', country: '秘鲁', name: 'Peru', phone: '51' },
        { suffix: '.pf', country: '法属玻利尼西亚', name: 'French Polynesia', phone: '689' },
        { suffix: '.pg', country: '巴布亚新几内亚', name: 'Papua New Guinea', phone: '675' },
        { suffix: '.ph', country: '菲律宾', name: 'Philippines', phone: '63' },
        { suffix: '.pk', country: '巴基斯坦', name: 'Pakistan', phone: '92' },
        { suffix: '.pl', country: '波兰', name: 'Poland', phone: '48' },
        { suffix: '.pr', country: '波多黎各', name: 'Puerto Rico', phone: '1787' },
        { suffix: '.pt', country: '葡萄牙', name: 'Portugal', phone: '351' },
        { suffix: '.py', country: '巴拉圭', name: 'Paraguay', phone: '595' },
        { suffix: '.qa', country: '卡塔尔', name: 'Qatar', phone: '974' },
        { suffix: '—', country: '留尼旺', name: 'Reunion', phone: '262' },
        { suffix: '.ro', country: '罗马尼亚', name: 'Romania', phone: '40' },
        { suffix: '.ru', country: '俄罗斯', name: 'Russia', phone: '7' },
        { suffix: '.sa', country: '沙特阿拉伯', name: 'Saudi Arabia', phone: '966' },
        { suffix: '.sb', country: '所罗门群岛', name: 'Solomon Is', phone: '677' },
        { suffix: '.sc', country: '塞舌尔', name: 'Seychelles', phone: '248' },
        { suffix: '.sd', country: '苏丹', name: 'Sudan', phone: '249' },
        { suffix: '.se', country: '瑞典', name: 'Sweden', phone: '46' },
        { suffix: '.sg', country: '新加坡', name: 'Singapore', phone: '65' },
        { suffix: '.si', country: '斯洛文尼亚', name: 'Slovenia', phone: '386' },
        { suffix: '.sk', country: '斯洛伐克', name: 'Slovakia', phone: '421' },
        { suffix: '.sl', country: '塞拉利昂', name: 'Sierra Leone', phone: '232' },
        { suffix: '.sm', country: '圣马力诺', name: 'San Marino', phone: '378' },
        { suffix: '.as', country: '美属萨摩亚', name: 'American Samoa', phone: '1684' },
        { suffix: '.ws', country: '萨摩亚', name: 'Samoa', phone: '685' },
        { suffix: '.sn', country: '塞内加尔', name: 'Senegal', phone: '221' },
        { suffix: '.so', country: '索马里', name: 'Somali', phone: '252' },
        { suffix: '.sr', country: '苏里南', name: 'Suriname', phone: '597' },
        { suffix: '.st', country: '圣多美和普林西比', name: 'Sao Tome and Principe', phone: '239' },
        { suffix: '.sv', country: '萨尔瓦多', name: 'EI Salvador', phone: '503' },
        { suffix: '.sy', country: '叙利亚', name: 'Syria', phone: '963' },
        { suffix: '.sz', country: '斯威士兰', name: 'Swaziland', phone: '268' },
        { suffix: '.td', country: '乍得', name: 'Chad', phone: '235' },
        { suffix: '.tg', country: '多哥', name: 'Togo', phone: '228' },
        { suffix: '.th', country: '泰国', name: 'Thailand', phone: '66' },
        { suffix: '.tj', country: '塔吉克斯坦', name: 'Tajikstan', phone: '992' },
        { suffix: '.tm', country: '土库曼斯坦', name: 'Turkmenistan', phone: '993' },
        { suffix: '.tn', country: '突尼斯', name: 'Tunisia', phone: '216' },
        { suffix: '.to', country: '汤加', name: 'Tonga', phone: '676' },
        { suffix: '.tr', country: '土耳其', name: 'Turkey', phone: '90' },
        { suffix: '.tt', country: '特立尼达和多巴哥', name: 'Trinidad and Tobago', phone: '1809' },
        { suffix: '.tw', country: '中国台湾省', name: 'Taiwan', phone: '886' },
        { suffix: '.tz', country: '坦桑尼亚', name: 'Tanzania', phone: '255' },
        { suffix: '.ua', country: '乌克兰', name: 'Ukraine', phone: '380' },
        { suffix: '.ug', country: '乌干达', name: 'Uganda', phone: '256' },
        { suffix: '.us', country: '美国', name: 'United States of America', phone: '1' },
        { suffix: '.uy', country: '乌拉圭', name: 'Uruguay', phone: '598' },
        { suffix: '.uz', country: '乌兹别克斯坦', name: 'Uzbekistan', phone: '998' },
        { suffix: '.vc', country: '圣文森特岛', name: 'Saint Vincent', phone: '1784' },
        { suffix: '.ve', country: '委内瑞拉', name: 'Venezuela', phone: '58' },
        { suffix: '.vn', country: '越南', name: 'Vietnam', phone: '84' },
        { suffix: '.ye', country: '也门', name: 'Yemen', phone: '967' },
        { suffix: '.yu', country: '南斯拉夫', name: 'Yugoslavia', phone: '381' },
        { suffix: '.za', country: '南非', name: 'South Africa', phone: '27' },
        { suffix: '.zm', country: '赞比亚', name: 'Zambia', phone: '260' },
        { suffix: '.zr', country: '扎伊尔', name: 'Zaire', phone: '243' },
        { suffix: '.zw', country: '津巴布韦', name: 'Zimbabwe', phone: '263' },
      ])
</script>
