<template>
  <tool-shell
    title="电话区号查询"
    desc="全球国家电话区号与时间差查询"
    icon="phone"
    color="#13C2C2"
    back-path="/tools/life"
  >
    <doc-list :rows="rows" :columns="columns" />
    <template #status>
      <span class="status-dot"></span>
      <span>{{ rows.length }} 条记录</span>
      <span class="status-right">支持搜索</span>
    </template>
  </tool-shell>
</template>

<script setup>
import { ref } from 'vue'
import ToolShell from '@/components/tool/ToolShell.vue'
import DocList from '@/components/tool/DocList.vue'

defineOptions({ name: 'LifeAreaCode' })

// 表格列配置：区号列等宽字体且支持点击复制
const columns = ref([
  { key: 'country', title: '国家或地区', tag: true },
  { key: 'name', title: '英文名称' },
  { key: 'phone', title: '电话区号', mono: true, copy: true },
  { key: 'code', title: '域名缩写', mono: true },
  { key: 'tz', title: '时差(相对北京时间)', mono: true }
])
// 全球国家区号数据，提取自旧项目 areaCode 模块
const rows = ref([
        { country: '安哥拉', name: 'Angola', phone: '244', code: 'AO', tz: '-7' },
        { country: '阿富汗', name: 'Afghanistan', phone: '93', code: 'AF', tz: '0' },
        { country: '阿尔巴尼亚', name: 'Albania', phone: '355', code: 'AL', tz: '-7' },
        { country: '阿尔及利亚', name: 'Algeria', phone: '213', code: 'DZ', tz: '-8' },
        { country: '安道尔共和国', name: 'Andorra', phone: '376', code: 'AD', tz: '-8' },
        { country: '安圭拉岛', name: 'Anguilla', phone: '1264', code: 'AI', tz: '-12' },
        { country: '安提瓜和巴布达', name: 'Antigua and Barbuda', phone: '1268', code: 'AG', tz: '-12' },
        { country: '阿根廷', name: 'Argentina', phone: '54', code: 'AR', tz: '-11' },
        { country: '亚美尼亚', name: 'Armenia', phone: '374', code: 'AM', tz: '-6' },
        { country: '阿森松', name: 'Ascension', phone: '247', code: '—', tz: '-8' },
        { country: '澳大利亚', name: 'Australia', phone: '61', code: 'AU', tz: '+2' },
        { country: '奥地利', name: 'Austria', phone: '43', code: 'AT', tz: '-7' },
        { country: '阿塞拜疆', name: 'Azerbaijan', phone: '994', code: 'AZ', tz: '-5' },
        { country: '巴哈马', name: 'Bahamas', phone: '1242', code: 'BS', tz: '-13' },
        { country: '巴林', name: 'Bahrain', phone: '973', code: 'BH', tz: '-5' },
        { country: '孟加拉国', name: 'Bangladesh', phone: '880', code: 'BD', tz: '-2' },
        { country: '巴巴多斯', name: 'Barbados', phone: '1246', code: 'BB', tz: '-12' },
        { country: '白俄罗斯', name: 'Belarus', phone: '375', code: 'BY', tz: '-6' },
        { country: '比利时', name: 'Belgium', phone: '32', code: 'BE', tz: '-7' },
        { country: '伯利兹', name: 'Belize', phone: '501', code: 'BZ', tz: '-14' },
        { country: '贝宁', name: 'Benin', phone: '229', code: 'BJ', tz: '-7' },
        { country: '百慕大群岛', name: 'Bermuda Is.', phone: '1441', code: 'BM', tz: '-12' },
        { country: '玻利维亚', name: 'Bolivia', phone: '591', code: 'BO', tz: '-12' },
        { country: '博茨瓦纳', name: 'Botswana', phone: '267', code: 'BW', tz: '-6' },
        { country: '巴西', name: 'Brazil', phone: '55', code: 'BR', tz: '-11' },
        { country: '文莱', name: 'Brunei', phone: '673', code: 'BN', tz: '0' },
        { country: '保加利亚', name: 'Bulgaria', phone: '359', code: 'BG', tz: '-6' },
        { country: '布基纳法索', name: 'Burkina-faso', phone: '226', code: 'BF', tz: '-8' },
        { country: '缅甸', name: 'Burma', phone: '95', code: 'MM', tz: '-1.3' },
        { country: '布隆迪', name: 'Burundi', phone: '257', code: 'BI', tz: '-6' },
        { country: '喀麦隆', name: 'Cameroon', phone: '237', code: 'CM', tz: '-7' },
        { country: '加拿大', name: 'Canada', phone: '1', code: 'CA', tz: '-13' },
        { country: '开曼群岛', name: 'Cayman Is.', phone: '1345', code: '—', tz: '-13' },
        { country: '中非共和国', name: 'Central African Republic', phone: '236', code: 'CF', tz: '-7' },
        { country: '乍得', name: 'Chad', phone: '235', code: 'TD', tz: '-7' },
        { country: '智利', name: 'Chile', phone: '56', code: 'CL', tz: '-13' },
        { country: '中国', name: 'China', phone: '86', code: 'CN', tz: '0' },
        { country: '哥伦比亚', name: 'Colombia', phone: '57', code: 'CO', tz: '0' },
        { country: '刚果', name: 'Congo', phone: '242', code: 'CG', tz: '-7' },
        { country: '库克群岛', name: 'Cook Is.', phone: '682', code: 'CK', tz: '-18.3' },
        { country: '哥斯达黎加', name: 'Costa Rica', phone: '506', code: 'CR', tz: '-14' },
        { country: '古巴', name: 'Cuba', phone: '53', code: 'CU', tz: '-13' },
        { country: '塞浦路斯', name: 'Cyprus', phone: '357', code: 'CY', tz: '-6' },
        { country: '捷克', name: 'Czech Republic', phone: '420', code: 'CZ', tz: '-7' },
        { country: '丹麦', name: 'Denmark', phone: '45', code: 'DK', tz: '-7' },
        { country: '吉布提', name: 'Djibouti', phone: '253', code: 'DJ', tz: '-5' },
        { country: '多米尼加共和国', name: 'Dominica Rep.', phone: '1890', code: 'DO', tz: '-13' },
        { country: '厄瓜多尔', name: 'Ecuador', phone: '593', code: 'EC', tz: '-13' },
        { country: '埃及', name: 'Egypt', phone: '20', code: 'EG', tz: '-6' },
        { country: '萨尔瓦多', name: 'EI Salvador', phone: '503', code: 'SV', tz: '-14' },
        { country: '爱沙尼亚', name: 'Estonia', phone: '372', code: 'EE', tz: '-5' },
        { country: '埃塞俄比亚', name: 'Ethiopia', phone: '251', code: 'ET', tz: '-5' },
        { country: '斐济', name: 'Fiji', phone: '679', code: 'FJ', tz: '+4' },
        { country: '芬兰', name: 'Finland', phone: '358', code: 'FI', tz: '-6' },
        { country: '法国', name: 'France', phone: '33', code: 'FR', tz: '-8' },
        { country: '法属圭亚那', name: 'French Guiana', phone: '594', code: 'GF', tz: '-12' },
        { country: '加蓬', name: 'Gabon', phone: '241', code: 'GA', tz: '-7' },
        { country: '冈比亚', name: 'Gambia', phone: '220', code: 'GM', tz: '-8' },
        { country: '格鲁吉亚', name: 'Georgia', phone: '995', code: 'GE', tz: '0' },
        { country: '德国', name: 'Germany', phone: '49', code: 'DE', tz: '-7' },
        { country: '加纳', name: 'Ghana', phone: '233', code: 'GH', tz: '-8' },
        { country: '直布罗陀', name: 'Gibraltar', phone: '350', code: 'GI', tz: '-8' },
        { country: '希腊', name: 'Greece', phone: '30', code: 'GR', tz: '-6' },
        { country: '格林纳达', name: 'Grenada', phone: '1809', code: 'GD', tz: '-14' },
        { country: '关岛', name: 'Guam', phone: '1671', code: 'GU', tz: '+2' },
        { country: '危地马拉', name: 'Guatemala', phone: '502', code: 'GT', tz: '-14' },
        { country: '几内亚', name: 'Guinea', phone: '224', code: 'GN', tz: '-8' },
        { country: '圭亚那', name: 'Guyana', phone: '592', code: 'GY', tz: '-11' },
        { country: '海地', name: 'Haiti', phone: '509', code: 'HT', tz: '-13' },
        { country: '洪都拉斯', name: 'Honduras', phone: '504', code: 'HN', tz: '-14' },
        { country: '香港', name: 'Hongkong', phone: '852', code: 'HK', tz: '0' },
        { country: '匈牙利', name: 'Hungary', phone: '36', code: 'HU', tz: '-7' },
        { country: '冰岛', name: 'Iceland', phone: '354', code: 'IS', tz: '-9' },
        { country: '印度', name: 'India', phone: '91', code: 'IN', tz: '-2.3' },
        { country: '印度尼西亚', name: 'Indonesia', phone: '62', code: 'ID', tz: '-0.3' },
        { country: '伊朗', name: 'Iran', phone: '98', code: 'IR', tz: '-4.3' },
        { country: '伊拉克', name: 'Iraq', phone: '964', code: 'IQ', tz: '-5' },
        { country: '爱尔兰', name: 'Ireland', phone: '353', code: 'IE', tz: '-4.3' },
        { country: '以色列', name: 'Israel', phone: '972', code: 'IL', tz: '-6' },
        { country: '意大利', name: 'Italy', phone: '39', code: 'IT', tz: '-7' },
        { country: '科特迪瓦', name: 'Ivory Coast', phone: '225', code: '—', tz: '-6' },
        { country: '牙买加', name: 'Jamaica', phone: '1876', code: 'JM', tz: '-12' },
        { country: '日本', name: 'Japan', phone: '81', code: 'JP', tz: '+1' },
        { country: '约旦', name: 'Jordan', phone: '962', code: 'JO', tz: '-6' },
        { country: '柬埔寨', name: 'Kampuchea (Cambodia )', phone: '855', code: 'KH', tz: '-1' },
        { country: '哈萨克斯坦', name: 'Kazakstan', phone: '327', code: 'KZ', tz: '-5' },
        { country: '肯尼亚', name: 'Kenya', phone: '254', code: 'KE', tz: '-5' },
        { country: '韩国', name: 'Korea', phone: '82', code: 'KR', tz: '+1' },
        { country: '科威特', name: 'Kuwait', phone: '965', code: 'KW', tz: '-5' },
        { country: '吉尔吉斯坦', name: 'Kyrgyzstan', phone: '331', code: 'KG', tz: '-5' },
        { country: '老挝', name: 'Laos', phone: '856', code: 'LA', tz: '-1' },
        { country: '拉脱维亚', name: 'Latvia', phone: '371', code: 'LV', tz: '-5' },
        { country: '黎巴嫩', name: 'Lebanon', phone: '961', code: 'LB', tz: '-6' },
        { country: '莱索托', name: 'Lesotho', phone: '266', code: 'LS', tz: '-6' },
        { country: '利比里亚', name: 'Liberia', phone: '231', code: 'LR', tz: '-8' },
        { country: '利比亚', name: 'Libya', phone: '218', code: 'LY', tz: '-6' },
        { country: '列支敦士登', name: 'Liechtenstein', phone: '423', code: 'LI', tz: '-7' },
        { country: '立陶宛', name: 'Lithuania', phone: '370', code: 'LT', tz: '-5' },
        { country: '卢森堡', name: 'Luxembourg', phone: '352', code: 'LU', tz: '-7' },
        { country: '澳门', name: 'Macao', phone: '853', code: 'MO', tz: '0' },
        { country: '马达加斯加', name: 'Madagascar', phone: '261', code: 'MG', tz: '-5' },
        { country: '马拉维', name: 'Malawi', phone: '265', code: 'MW', tz: '-6' },
        { country: '马来西亚', name: 'Malaysia', phone: '60', code: 'MY', tz: '-0.5' },
        { country: '马尔代夫', name: 'Maldives', phone: '960', code: 'MV', tz: '-7' },
        { country: '马里', name: 'Mali', phone: '223', code: 'ML', tz: '-8' },
        { country: '马耳他', name: 'Malta', phone: '356', code: 'MT', tz: '-7' },
        { country: '马里亚那群岛', name: 'Mariana Is', phone: '1670', code: '—', tz: '+1' },
        { country: '马提尼克', name: 'Martinique', phone: '596', code: '—', tz: '-12' },
        { country: '毛里求斯', name: 'Mauritius', phone: '230', code: 'MU', tz: '-4' },
        { country: '墨西哥', name: 'Mexico', phone: '52', code: 'MX', tz: '-15' },
        { country: '摩尔多瓦', name: 'Moldova, Republic of', phone: '373', code: 'MD', tz: '-5' },
        { country: '摩纳哥', name: 'Monaco', phone: '377', code: 'MC', tz: '-7' },
        { country: '蒙古', name: 'Mongolia', phone: '976', code: 'MN', tz: '0' },
        { country: '蒙特塞拉特岛', name: 'Montserrat Is', phone: '1664', code: 'MS', tz: '-12' },
        { country: '摩洛哥', name: 'Morocco', phone: '212', code: 'MA', tz: '-6' },
        { country: '莫桑比克', name: 'Mozambique', phone: '258', code: 'MZ', tz: '-6' },
        { country: '纳米比亚', name: 'Namibia', phone: '264', code: 'NA', tz: '-7' },
        { country: '瑙鲁', name: 'Nauru', phone: '674', code: 'NR', tz: '+4' },
        { country: '尼泊尔', name: 'Nepal', phone: '977', code: 'NP', tz: '-2.3' },
        { country: '荷属安的列斯', name: 'Netheriands Antilles', phone: '599', code: '—', tz: '-12' },
        { country: '荷兰', name: 'Netherlands', phone: '31', code: 'NL', tz: '-7' },
        { country: '新西兰', name: 'New Zealand', phone: '64', code: 'NZ', tz: '+4' },
        { country: '尼加拉瓜', name: 'Nicaragua', phone: '505', code: 'NI', tz: '-14' },
        { country: '尼日尔', name: 'Niger', phone: '227', code: 'NE', tz: '-8' },
        { country: '尼日利亚', name: 'Nigeria', phone: '234', code: 'NG', tz: '-7' },
        { country: '朝鲜', name: 'North Korea', phone: '850', code: 'KP', tz: '+1' },
        { country: '挪威', name: 'Norway', phone: '47', code: 'NO', tz: '-7' },
        { country: '阿曼', name: 'Oman', phone: '968', code: 'OM', tz: '-4' },
        { country: '巴基斯坦', name: 'Pakistan', phone: '92', code: 'PK', tz: '-2.3' },
        { country: '巴拿马', name: 'Panama', phone: '507', code: 'PA', tz: '-13' },
        { country: '巴布亚新几内亚', name: 'Papua New Cuinea', phone: '675', code: 'PG', tz: '+2' },
        { country: '巴拉圭', name: 'Paraguay', phone: '595', code: 'PY', tz: '-12' },
        { country: '秘鲁', name: 'Peru', phone: '51', code: 'PE', tz: '-13' },
        { country: '菲律宾', name: 'Philippines', phone: '63', code: 'PH', tz: '0' },
        { country: '波兰', name: 'Poland', phone: '48', code: 'PL', tz: '-7' },
        { country: '法属玻利尼西亚', name: 'French Polynesia', phone: '689', code: 'PF', tz: '+3' },
        { country: '葡萄牙', name: 'Portugal', phone: '351', code: 'PT', tz: '-8' },
        { country: '波多黎各', name: 'Puerto Rico', phone: '1787', code: 'PR', tz: '-12' },
        { country: '卡塔尔', name: 'Qatar', phone: '974', code: 'QA', tz: '-5' },
        { country: '留尼旺', name: 'Reunion', phone: '262', code: '—', tz: '-4' },
        { country: '罗马尼亚', name: 'Romania', phone: '40', code: 'RO', tz: '-6' },
        { country: '俄罗斯', name: 'Russia', phone: '7', code: 'RU', tz: '-5' },
        { country: '圣卢西亚', name: 'Saint Lueia', phone: '1758', code: 'LC', tz: '-12' },
        { country: '圣文森特岛', name: 'Saint Vincent', phone: '1784', code: 'VC', tz: '-12' },
        { country: '东萨摩亚(美)', name: 'Samoa Eastern', phone: '684', code: '—', tz: '-19' },
        { country: '西萨摩亚', name: 'Samoa Western', phone: '685', code: '—', tz: '-19' },
        { country: '圣马力诺', name: 'San Marino', phone: '378', code: 'SM', tz: '-7' },
        { country: '圣多美和普林西比', name: 'Sao Tome and Principe', phone: '239', code: 'ST', tz: '-8' },
        { country: '沙特阿拉伯', name: 'Saudi Arabia', phone: '966', code: 'SA', tz: '-5' },
        { country: '塞内加尔', name: 'Senegal', phone: '221', code: 'SN', tz: '-8' },
        { country: '塞舌尔', name: 'Seychelles', phone: '248', code: 'SC', tz: '-4' },
        { country: '塞拉利昂', name: 'Sierra Leone', phone: '232', code: 'SL', tz: '-8' },
        { country: '新加坡', name: 'Singapore', phone: '65', code: 'SG', tz: '+0.3' },
        { country: '斯洛伐克', name: 'Slovakia', phone: '421', code: 'SK', tz: '-7' },
        { country: '斯洛文尼亚', name: 'Slovenia', phone: '386', code: 'SI', tz: '-7' },
        { country: '所罗门群岛', name: 'Solomon Is', phone: '677', code: 'SB', tz: '+3' },
        { country: '索马里', name: 'Somali', phone: '252', code: 'SO', tz: '-5' },
        { country: '南非', name: 'South Africa', phone: '27', code: 'ZA', tz: '-6' },
        { country: '西班牙', name: 'Spain', phone: '34', code: 'ES', tz: '-8' },
        { country: '斯里兰卡', name: 'Sri Lanka', phone: '94', code: 'LK', tz: '0' },
        { country: '圣卢西亚', name: 'St.Lucia', phone: '1758', code: 'LC', tz: '-12' },
        { country: '圣文森特', name: 'St.Vincent', phone: '1784', code: 'VC', tz: '-12' },
        { country: '苏丹', name: 'Sudan', phone: '249', code: 'SD', tz: '-6' },
        { country: '苏里南', name: 'Suriname', phone: '597', code: 'SR', tz: '-11.3' },
        { country: '斯威士兰', name: 'Swaziland', phone: '268', code: 'SZ', tz: '-6' },
        { country: '瑞典', name: 'Sweden', phone: '46', code: 'SE', tz: '-7' },
        { country: '瑞士', name: 'Switzerland', phone: '41', code: 'CH', tz: '-7' },
        { country: '叙利亚', name: 'Syria', phone: '963', code: 'SY', tz: '-6' },
        { country: '台湾省', name: 'Taiwan', phone: '886', code: 'TW', tz: '0' },
        { country: '塔吉克斯坦', name: 'Tajikstan', phone: '992', code: 'TJ', tz: '-5' },
        { country: '坦桑尼亚', name: 'Tanzania', phone: '255', code: 'TZ', tz: '-5' },
        { country: '泰国', name: 'Thailand', phone: '66', code: 'TH', tz: '-1' },
        { country: '多哥', name: 'Togo', phone: '228', code: 'TG', tz: '-8' },
        { country: '汤加', name: 'Tonga', phone: '676', code: 'TO', tz: '+4' },
        { country: '特立尼达和多巴哥', name: 'Trinidad and Tobago', phone: '1809', code: 'TT', tz: '-12' },
        { country: '突尼斯', name: 'Tunisia', phone: '216', code: 'TN', tz: '-7' },
        { country: '土耳其', name: 'Turkey', phone: '90', code: 'TR', tz: '-6' },
        { country: '土库曼斯坦', name: 'Turkmenistan', phone: '993', code: 'TM', tz: '-5' },
        { country: '乌干达', name: 'Uganda', phone: '256', code: 'UG', tz: '-5' },
        { country: '乌克兰', name: 'Ukraine', phone: '380', code: 'UA', tz: '-5' },
        { country: '阿拉伯联合酋长国', name: 'United Arab Emirates', phone: '971', code: 'AE', tz: '-4' },
        { country: '英国', name: 'United Kiongdom', phone: '44', code: 'GB', tz: '-8' },
        { country: '美国', name: 'United States of America', phone: '1', code: 'US', tz: '-13' },
        { country: '乌拉圭', name: 'Uruguay', phone: '598', code: 'UY', tz: '-10.3' },
        { country: '乌兹别克斯坦', name: 'Uzbekistan', phone: '233', code: 'UZ', tz: '-5' },
        { country: '委内瑞拉', name: 'Venezuela', phone: '58', code: 'VE', tz: '-12.3' },
        { country: '越南', name: 'Vietnam', phone: '84', code: 'VN', tz: '-1' },
        { country: '也门', name: 'Yemen', phone: '967', code: 'YE', tz: '-5' },
        { country: '南斯拉夫', name: 'Yugoslavia', phone: '381', code: 'YU', tz: '-7' },
        { country: '津巴布韦', name: 'Zimbabwe', phone: '263', code: 'ZW', tz: '-6' },
        { country: '扎伊尔', name: 'Zaire', phone: '243', code: 'ZR', tz: '-7' },
        { country: '赞比亚', name: 'Zambia', phone: '260', code: 'ZM', tz: '-6' },
      ])
</script>
